ollama_base_url: "http://ollama:11434"

model: "deepseek-r1:70b"

models: 
  #- "mistral:7b" -> svalvola
  #- "mistral-nemo" -> svalvola
  #- "llama3.1:8b"
  #- "llama3.3:70b" 
  #- "codellama:70b" -> svalvola
  #- "codellama:13b" 
  #- "qwen2.5:7b" -> svalvola
  #- "qwen3:14b"
  - "deepseek-r1:70b"
  #- "deepseek-v4-flash:cloud" -> unauthorized
  #- "qwen2.5-coder:14B"
  #- "deepseek-coder-v2"

temperature: 0.1

seed: 42

runs_per_case: 1
max_retries: 3
request_timeout_sec: 180
warmup: true
set : "validation"
reasoning : true

# Extra options passed to Ollama /api/generate
options:
  num_ctx: 4096
  top_p: 0.9
  top_k: 40
  repeatPenalty: 1.1

prompt_config:
  identify_sections: "v1"
  understand_section: "rv2"
  understand_sections: "v1"
  check_balance: "rv2"
  generate_trace_ideas: "rv1"
  generate_trace: "v1"
  verify_trace: "v1"
  classification: "v1"